image: nixos/nix:2.9.1

variables:
  NIX_CONFIG: "experimental-features = nix-command flakes"

before_script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use felschr

stages:
  - test
  - build

check:
  stage: test
  script:
    - cachix watch-exec felschr nix flake check --no-build

build:
  stage: build
  script:
    - cachix watch-exec felschr nix build .#deconz
    - cachix watch-exec felschr nix build .#nixosConfigurations.home-server.config.system.build.toplevel
    # disabled because GitLab.com runner runs out of space
    # - cachix watch-exec felschr nix build .#nixosConfigurations.home-pc.config.system.build.toplevel
  only:
    - main
  allow_failure: true
