image: nixos/nix:2.9.1

variables:
  NIX_CONFIG: "experimental-features = nix-command flakes"

build:
  stage: build
  allow_failure: true
  before_script:
    - nix-env -iA cachix -f https://cachix.org/api/v1/install
    - cachix use felschr
  script:
    - cachix watch-exec felschr nix build .#nixosConfigurations.home-pc.config.system.build.toplevel
    - cachix watch-exec felschr nix build .#nixosConfigurations.home-server.config.system.build.toplevel
  only:
    - main
