name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: native
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      # - uses: https://github.com/cachix/cachix-action@v15
      #   with:
      #     name: felschr
      #     authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      # - run: nix flake check
      - run: nix build .#brlaser
      - run: nix build .#deconz
      - run: nix build .#nixosConfigurations.home-server.config.system.build.toplevel
      - run: nix build .#nixosConfigurations.home-pc.config.system.build.toplevel
