nnoremap <leader>dc <cmd>lua require'dap'.continue()<CR>
nnoremap <leader>db <cmd>lua require'dap'.toggle_breakpoint()<CR>
nnoremap <leader>do <cmd>lua require'dap'.step_over()<CR>
nnoremap <leader>di <cmd>lua require'dap'.step_into()<CR>
nnoremap <leader>dO <cmd>lua require'dap'.step_out()<CR>
nnoremap <leader>dh <cmd>lua require'dap'.goto()<CR>
nnoremap <leader>dk <cmd>lua require'dap.ui.variables'.hover()<CR>
nnoremap <leader>dr <cmd>lua require'dap'.repl.open()<CR>
nnoremap <leader>dl <cmd>lua require'dap'.repl.run_last()<CR>
